### ISSUE TITLE
Credit Packages translation - alignment - value

### ISSUE THREAD

**Issue by CurlyGiac** [Aleolly/AppIssues#1]
Inside PRO profile / Credit points packages:
Packages name is in English while the page is in Arabic
I see the information is not aligned
Also the value x credit is wrong. should be 5 / 5 / 4.5 / 5

Mobile Pack
باقة الجوال

Starting Pack
باقة البداية

Standard Pack
الباقة النموذجية

Offer Pack
باقة العرض

**Comment by Aleolly** [comment]
Offer pack is set to 50 credits for 210 SAR, it can't be 5 SAR per credit.
Check titles (just close and reopen current app) and let me know what I have to do about Offer pack settings.

**Comment by CurlyGiac** [comment]
Fixed
